AWSTemplateFormatVersion: "2010-09-09"
Description: This template deploys an ECS Fargate cluster with an Amazon Linux image.
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select your VPC. If you are using the VPC from the CD tutorial, select the mwaa-cicd VPC.
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select your subnet. If you are using the subnet from the CD tutorial, select mwaa-cicd-Public Subnet (AZ1).
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Select your security group. If you are using the security group from the CD tutorial, select the mwaa-cicd security group.
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${AWS::StackName}"

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 30

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${AWS::StackName}"
      Cpu: 2048
      Memory: 4096
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: !Sub "${AWS::StackName}"
          Image: 070773293015.dkr.ecr.us-west-2.amazonaws.com/mwaa-cicd:2.0.2
          PortMappings:
            - Protocol: tcp
              ContainerPort: 8080
              HostPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
      RequiresCompatibilities:
        - FARGATE

  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub "${AWS::StackName}"
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      PlatformVersion: 1.3.0
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups: !Ref SecurityGroups
